[package]
name = "rusty-can-fuzzer"
version = "0.1.0"
authors = ["TheDragonMask <andrew.niven95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
